theme: jekyll-theme-minimal
title: Julia H. Yang
logo: headshot-ucb.png
description: Computational materials scientist working closely with experiments to address 
             urgently-needed solutions for energy storage and the environment. 
             Postdoc at Harvard University, Ph.D. from U.C. Berkeley.


